apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: paios-ingress
  namespace: paios
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: "letsencrypt"
spec:
  tls:
  - hosts:
    - paios.io
    secretName: paios-tls
  rules:
  - host: paios.io
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: paios-backend
            port:
              number: 8000
      - path: /
        pathType: Prefix
        backend:
          service:
            name: paios-frontend
            port:
              number: 3000
